### PR TITLE
feat: add Infracost project tree view

### PR DESCRIPTION
**Pull request by hugorut**
Add support for custom Infracost tree view. Accessible from the VSCode sidebar.

SCR-20220710-l1i-2

Provides a simple way for users to navigate their costs from the editor:
 
tree-view

This feature also adds support for new project detection, by adding a hard refresh button. This is a workaround for new projects until we add a `detect` or similar functionality within the CLI or future LS.

### CODE REVIEW

**Comment by hugorut** [comment]
@aliscott I've run the prettier formatter against this branch so hopefully there won't be too many conflicts. I'll wait till we merge your PR and then rebase the changes onto this branch.

**Comment by aliscott** [comment]
> @aliscott I've run the prettier formatter against this branch so hopefully there won't be too many conflicts. I'll wait till we merge your PR and then rebase the changes onto this branch.

Cheers, that's in now. Sorry for all the conflicts...

giphy-downsized-large

**Comment by hugorut** [comment]
rebasing hell over

**Review by aliscott — APPROVED** [review]
Look awesome!

**Pull request merged**
